on: [push]

jobs:
  where_s_waldo_job:
    runs-on: ubuntu-latest
    name: A job to test "Where's Waldo "
    steps:
      - name: Where's Waldo?
        id: waldo
        uses: alexnaiman/where-s-waldo-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}